version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - "81:80"
    volumes:
      - /home/bruno/dev/Apache:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge